### ISSUE TITLE
Ni🅱️🅱️a this doesn't work

### ISSUE THREAD

**Issue by jlxip** [krashanoff/to65536#1]
Tested on Firefox and Chrome.

**Comment by krashanoff** [comment]
Repository has been dead for a while now as I had trouble getting it working two some years ago, but I'll give it my best shot.

**Comment by krashanoff** [comment]
I know that this is almost a year late and probably completely pointless, but for what it's worth, I tried to at least make the website usable. It works on Chrome and Firefox, but it is not working on Edge. This is something that can be resolved later, though, as I think that Edge just doesn't play nice with the way the website uses the node module for base65536.
